spring.application.name=spring-boot-i18n-demo

smart.i18n.enabled=true
smart.i18n.source-locale=en
#smart.i18n.provider.active=gemini
#smart.i18n.gemini.api-key=${GEMINI_API_KEY}
#smart.i18n.gemini.model=gemini-2.5-flash-lite
#smart.i18n.provider.active=openai
#smart.i18n.openai.api-key=${OPENAI_API_KEY}
#smart.i18n.openai.model=gpt-4o-mini
smart.i18n.provider.active=google-cloud
smart.i18n.google-cloud.api-key=${GOOGLE_CLOUD_API_KEY}
smart.i18n.logging=debug
smart.i18n.provider.timeout-ms=3000